const commiteeMap = {
  1: "Arrkom",
  2: "Bankom",
  3: "Bedkom",
  4: "Dotkom",
  5: "Ekskom",
  6: "Fagkom",
  7: "Prokom",
  8: "Trikom",
  9: "Velkom",
  10: "Pangkom",
  11: "HS",
  12: "Komiteer",
  13: "Æresmedlemmer",
  14: "Eldsterådet",
  16: "Appkom",
  17: "Bed&Fagkom",
  18: "Backlog",
  19: "Jubkom",
  20: "Faddere",
  21: "Redaksjonen",
  22: "Wiki - Online edit permissions",
  23: "Wiki - Komiteer access permissions",
  24: "ITEX",
  26: "kobKom",
  27: "Riddere",
  28: "Tillitsvalgte",
  29: "Fond",
  30: "Buddy",
  31: "Ex-Hovedstyret",
  32: "Eksgruppa",
  33: "Kjelleren",
  34: "interessegrupper",
  35: "Ex-Komiteer",
  36: "Online-IL",
  37: "techtalks",
  38: "booking",
  39: "X-Sport",
  40: "Output",
  41: "Komiteledere",
  42: "CAG",
  43: "ITEX-påmeldte",
  45: "Bekk_påmeldte",
  47: "Debug",
};

export default commiteeMap;
